version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: django-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot_history
      - GROQ_API_KEY=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
      # Add any other environment variables your Django app needs
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: lanchain-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

  mongo:
    image: mongo:latest
    container_name: lanchain-mongo-1
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=your_secure_password
volumes:
  mongo_data:
networks:
  default:
    name: lanchain_default