version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: django-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot_history
    ports:
      - "8000:8000"
    image: us-central1-docker.pkg.dev/beaming-botany-457907-b7/version01/backendv03:latest  

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: lanchain-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    image: us-central1-docker.pkg.dev/beaming-botany-457907-b7/version01/frontendv03:latest   # <-- Replace with your GCP project and repo

  mongo:
    image: mongo:latest
    container_name: lanchain-mongo-1
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  default:
    name: lanchain_default
